Name to ID
telia-oss/terraform-aws-lambda pull request #4
Opened 2018-09-07 09:20 UTC by colincoleman

2018-09-07 09:39 UTC, mikael-lindstrom requested changes
Won't this break backwards compatibility if people are using the `role_name` now?

2018-09-07 09:39 UTC, mikael-lindstrom commented on outputs.tf
>    description = "The name of the execution role."
If this now is the id the description should reflect this.

2018-09-07 12:20 UTC, colincoleman commented
This change is to address this issue:
telia-oss/terraform-aws-ecs#7

2018-09-09 21:03 UTC, mikael-lindstrom commented on outputs.tf
> +  value       = "${aws_iam_role.main.id}"
Shouldn't this be `unique_id`?

2019-04-26 11:55 UTC, closed without merging